### ISSUE TITLE
How to test rails associations with mocks?

### ISSUE THREAD

**Issue by st0mir** [freerange/mocha#234]
I have class that is responsible for doing some processing:

```ruby
class Processor < ActiveRecord::Base
  def process
    # do some stuff
  end
end
```

and another class that is responsible for executing every processor and concatenating result. It's important to execute processors in correct order:
```ruby
class ProcessorSet < ActiveRecord::Base
  has_many :processors, -> { order(:priority) }

  def process
    processors.map do |processor|
      processor.process
    end.join
  end      
end
```

How to test ProcessorSet.process method without having dependency with Processor (I don't want to test Process.process method, because it's already tested in another test unit). I've tried to mock processors as following:
```ruby
class ProcessorSetTest < ActiveSupport::TestCase
  processor_set = ProcessorSet.new

  processors = ['result1', 'result2'].map do |result|
    object = mock()
    object.expects(:process).returns(result)
    object
  end

  processor_set.expects(:processors).returns(processors)

  assert_equal 'result1result2', processor_set.process
end
```

But how in such case test that processors are returned in correct order?

**Comment by floehopper** [comment]
I think you should be able to use [Mocha::API#sequence](http://gofreerange.com/mocha/docs/Mocha/API.html#sequence-instance_method) and [Mocha::Expectation#in_sequence](http://gofreerange.com/mocha/docs/Mocha/Expectation.html#in_sequence-instance_method) to constrain the order of invocation some along these lines:

```ruby
class ProcessorSetTest < ActiveSupport::TestCase
  processor_set = ProcessorSet.new

  processing = sequence(:processing)
  processors = ['result1', 'result2'].map do |result|
    object = mock()
    object.expects(:process).returns(result).in_sequence(:processing)
    object
  end

  processor_set.expects(:processors).returns(processors)

  assert_equal 'result1result2', processor_set.process
end
```

Personally, I'd probably stub rather than expect the call to `ProcessorSet#processors`, because it's a "query" rather than a "command".

Also, since you're already stubbing `ProcessorSet#processors`, you could introduce a new method on `ProcessorSet` to explicitly return the `Processor` instances in the order that you want. And then stub that method instead and add a separate test to assert they are returned in the correct order.

Please close this issue if the solution suggested above works ok.

**Comment by bjarosze** [comment]
But what advantages I get having such test? I can remove code responsible for ordering (```-> { order(:priority) }```) and test will still pass.

I think I will test ordering with real data and database (maybe this is the correct why since ordering happens on database).

**Comment by st0mir** [comment]
But what advantages I get by having such test? I can remove code responsible for ordering (``` -> { order(:priority) }```) and test will still pass.

I think I will test ordering with real data and database (maybe this is the correct way since ordering happens on database).

**Comment by floehopper** [comment]
Yes. I think that's the correct approach.
