### ISSUE TITLE
getting test errors when switching from mocha/setup to mocha/api

### ISSUE THREAD

**Issue by jsgarvin** [freerange/mocha#239]
I'm working on upgrading a legacy rails app with some cucumber tests that use Mocha's `any_instance` construct. As is, the tests pass, but I'm getting a deprecation warning from the test setup to use `require 'mocha/api'` instead of `require 'mocha/setup'`.  However, when I make that switch, the tests begin throwing `undefined method `any_instance'` errors.   Any thoughts on what might be going wrong here would be appreciated.

**Comment by floehopper** [comment]
Can you post the relevant Cucumber test setup code that you mention. It sounds as if the `Mocha::API` module is not being included into your test context.

It's a while since I've used Cucumber (especially in combination with mocking), but I'd expect you'd need something like this:

```ruby
require 'mocha/api'

World(Mocha::API)

Before do
  mocha_setup
end

After do
  begin
    mocha_verify
  ensure
    mocha_teardown
  end
end
```

Note that the Cucumber syntax may be out-of-date.

**Comment by floehopper** [comment]
@jsgarvin: Did any of that help? Please close the issue if you're happy with the response.

**Comment by jsgarvin** [comment]
@floehopper  Sorry, just managing to circle back around to this.   Thanks for the quick response.

I tried adding those lines to features/support/env.rb, but I still get the same error.    I'll try to come up with a small test case to demonstrate with.  I'll close this for now and re-open when I have more to work with.

**Comment by floehopper** [comment]
OK. I would've assumed you *already* had something like that in `env.rb` or similar, so that might explain why just adding what I posted didn't help i.e. you probably ought to be *replacing* some old code with the code I posted. Anyway, thanks for getting back to me and let me know if you need more help.
