### ISSUE TITLE
Instance variables from the test case are not available inside API#stub block

### ISSUE THREAD

**Issue by ggaston095** [freerange/mocha#286]
I think this is some kind of bug. I don't know why stub2 can't see stub1
```ruby
test "test1" do 
  @stub1 = stub do
    stubs(:method1).returns(0)
  end 
  stub2 = stub do 
    #error, @stub1 is nil
    stubs(:find_by_id).with(@stub1.method1).returns(@stub1)
  end
end
```

**Comment by floehopper** [comment]
@ggaston095: I hope you don't mind, but I've tidied up the formatting of your code and switched on Ruby syntax highlighting to make things clearer.

**Comment by floehopper** [comment]
@ggaston095: I've also renamed the issue to better explain the problem.

**Comment by floehopper** [comment]
@ggaston095:

I've investigated this a little. The block passed to the `Mocha::API#stub` method is currently evaluated using `BasicObject#instance_eval`, so the block is evaluated in the context of the newly instantiated stub object and not in the context of the test case instance. This is why the instance variable from the outer context is not available inside the block.

I can see how this is confusing and I will have a think about what the best solution is. At the very least we should update the documentation to make it clearer what the current behaviour is.

Presumably the code you included in the description was example code and not real code. In case it's real code, you could solve your immediate problem by using a local variable (`stub1`) instead of the instance variable, `@stub1`.

**Comment by ggaston095** [comment]
Thanks. I'll stick with the local variable for now :)

**Comment by floehopper** [comment]
The relevant documentation has been improved and the mechanism itself has been deprecated in #290. These change will go out in the next release. Closing.
