### ISSUE TITLE
Prevent calls to Mocha::API methods until the before/setup block for a single test/example

### ISSUE THREAD

**Issue by andyw8** [freerange/mocha#292]
I'm working on a relatively old Rails codebase which uses Mocha with RSpec.

There is some instability in the test suite which is caused by stubbing happening in `before(:all)` blocks:

https://gist.github.com/andyw8/7aa312287dd5c60412475a147900e121

If I attempt the same thing with rspec-mocks, it refuses to run:

`The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported.`

https://relishapp.com/rspec/rspec-mocks/docs/basics/scope#cannot-create-doubles-in-a-`before(:context)`-hook

Is it possible to have a similar level of protection when using mocha? I'm not sure if this code would belong in Mocha, in RSpec, or perhaps a separate gem.

**Comment by floehopper** [comment]
@andyw8: Sorry, we've been away over the Christmas period. We'll try to get back to you as soon as we can.

**Comment by floehopper** [comment]
@andyw8:

Hi. Sorry for the slow reply. Thanks for raising this issue and explaining it clearly.

> Is it possible to have a similar level of protection when using mocha?

This is not currently possible with Mocha. However, it does sound like a sensible idea.

Currently the [Mocha::Mockery](https://github.com/freerange/mocha/blob/master/lib/mocha/mockery.rb) singleton is lazily instantiated when the first call is made to a method in [Mocha::API](http://gofreerange.com/mocha/docs/Mocha/API.html). In order to implement the behaviour you describe, I think we'd want the Mockery to be in some "unusable" state until the point where the test library calls [Mocha::Hooks#mocha_setup](http://gofreerange.com/mocha/docs/Mocha/Hooks.html#mocha_setup-instance_method). If any calls are made to the Mockery when it's in this "unusable" state, it could raise an exception like [RSpec::Mocks:: OutsideOfExampleError](https://github.com/rspec/rspec-mocks/blob/915b15bc8f1fe43002aa2fbf5e8c2c842ea5052f/lib/rspec/mocks/error_generator.rb#L13).

Rather than introducing a new state into the Mockery, it might be more sensible to use the Null Object pattern and have some kind of NullMockery class which raises the exception c.f. [RSpec::Mocks::RootSpace](https://github.com/rspec/rspec-mocks/blob/008caa061a1bac7eff23ce53b4c8bd7b6be81ba0/lib/rspec/mocks/space.rb#L9).

It's worth noting that we'd need to ensure any such solution worked with Test::Unit and Minitest which are the two libraries which Mocha explicitly supports. However, since RSpec and the adapters for both of these libraries already call Mocha::Hooks#mocha_setup, I don't think this should be an issue.

Anyway, having thought about it, I'm happy to label this issue as a "feature-request". I don't think implementing it should be _too_ hard, but it's not trivial either. So I'm not sure how soon we'll be able to work on it.

For the moment, can you work around the issue by finding all the calls to Mocha::API methods within `before(:all)` blocks and move them to `before(:each)` blocks? Are you having trouble finding all the occurrences? Let us know if it's causing you a big problem and we'll see whether we can help.

**Comment by floehopper** [comment]
I've renamed the issue to so it's no longer RSpec-specific.

**Comment by andyw8** [comment]
@floehopper thanks for looking into this. Moving the calls from `before(:all)` to `before(:each)` blocks is the approach I've taken, but I'd like to protect against any future occurrences.

**Comment by floehopper** [comment]
I've done a bit of spiking on this and I think I have the basis of a solution working: https://github.com/freerange/mocha/compare/spike-fail-fast-if-mocking-before-setup

However, this work has highlighted a shortcoming in the current acceptance tests. It appears that both the outer and inner tests are interacting with the Mockery. This means that `Mockery#teardown` is called twice for each test - first at the end of the inner test and then at the end of the outer test. Ideally the outer test would not use Mocha at all and so I've created a new issue to fix that: #293.

Although it's causing most/all of the acceptance tests to fail, I don't think that's indicative of an actual problem with Mocha.

**Comment by floehopper** [comment]
Note that `Test::Unit::TestCase.startup` is the equivalent of `before(:all)`. However, by default `Mocha::API` is not available to singleton methods of `TestCase`, so the original problem is less likely to arise.

**Comment by andyw8** [comment]
Thanks for this @floehopper. I'll try pointing my Gemfile to this branch and running the tests.

**Comment by floehopper** [comment]
I'm sorry for the delay in making any more progress on this. I'm going to rebase the spike branch against `master` and open it as a WIP PR in order to continue to work on it.

**Comment by floehopper** [comment]
I've now opened the changes in the spike branch as #319.

**Comment by andyw8** [comment]
@floehopper Thanks. We're still using Mocha so it would be great to have this.

**Comment by floehopper** [comment]
@lzap has reported a very similar issue in #326.

**Comment by lzap** [comment]
Thanks, subscribed. I will try your patch to see if it shows something reasonable on my suite.

**Comment by floehopper** [comment]
@andyw8, @lzap:

I've just opened #327 as a proper fix for this. I'd be really grateful if you could try [that branch][1] out on your project and see whether it works OK.

I'm sorry (especially to @andyw8) that it's taken so long for me to get round to this, but this is the first time in ages I've had a significant chunk of time to spend on Mocha.

[1]: https://github.com/freerange/mocha/compare/prevent-use-of-mocha-outside-test

**Comment by andyw8** [comment]
Thanks @floehopper. I appreciate the effort. I'll try this on our project as soon as I can.

**Comment by floehopper** [comment]
I've released the fix in v1.5.0.
