### ISSUE TITLE
Class method like any_instance but guarded by a block

### ISSUE THREAD

**Issue by stripedpumpkin** [freerange/mocha#296]
We probably agree that the following is a bad test, because we are not testing that the reviewer with id 1 is receiving the paper. As far as the test goes, any other reviewer could have got the paper.

```ruby
  def test_reviewer_is_notified
    paper = Paper.new
    paper.reviewer_id = 1
    Reviewer.any_instance.expects(:email).with(paper).once
    paper.notify_reviewer
  end
```

If we are using a framework like Active::Record we could mock something like ActiveRecord::Base.find

```ruby
  def test_reviewer_is_notified
    paper = Paper.new
    paper.reviewer_id = 1
    reviewer = Reviewer.new
    Reviewer.expects(:find).with(1).once.returns(reviewer)
    reviewer.expects(:email).with(paper).once
    paper.notify_reviewer
  end
```

But this is arguably bad for two reasons:

- It is too tight: this is testing the implementation rather than testing the desired behavior only
- We are mocking something we are not owning, hence not testing directly

In some cases we might accept to change the specified behavior:

```ruby
  def test_reviewer_is_notified
    paper = Paper.new
    reviewer = Reviewer.new
    paper.reviewer = reviewer
    reviewer.expects(:email).with(paper).once
    paper.notify_reviewer
  end
```

But there are many cases where this is definitely not equivalent such as when the assignment happens asynchronously at a time it is uncertain whether the reviewer record exists already.

```ruby
  def test_reviewer_is_notified
    paper = Paper.new
    paper.reviewer_email = 'john.doe@example.org'

    assert_raises ReviewerNotFound { paper.notify_reviewer }

    reviewer = Reviewer.new(
      email: 'john.doe@example.org'
    )
    reviewer.expects(:email).with(paper).once
    paper.notify_reviewer
  end
```

Coming back to the initial example, we could argue that the desired test is something like:

```ruby
  def test_reviewer_is_notified
    paper = Paper.new
    paper.reviewer_id = 1
    Reviewer.such_that { |reviewer| reviewer.id == 1 }.expects(:email).with(paper).once
    paper.notify_reviewer
  end
```

Is something like that already possible in mocha? If not, is it desirable? This could maybe even be a block passed to any_instance.

**Comment by floehopper** [comment]
@stripedpumpkin: Thanks for your suggestion. We'll try to look at this properly when we have some spare time.

**Comment by floehopper** [comment]
@stripedpumpkin:

I'm really sorry it's taken us so long to get back to you. Thanks for taking the time to open the issue and illustrate it with code examples.

That being said, I'm not convinced the problem you are describing is actually a problem; it's certainly not one that I've run into nor one that other people have reported to me.

What's more, I tend to avoid using [`Mocha::ClassMethods#any_instance`][1] as much as possible, because I think usually makes tests more confusing and is often a sign of a problem with the design of the code under test. In fact, in many ways, I wish I'd never added it to Mocha!

Given all the above, it's not very appealing to me to further complicate the implementation of `Mocha::ClassMethods#any_instance`, so I'm afraid I'm going to mark this as `wont-fix` and close the issue.

[1]: http://gofreerange.com/mocha/docs/Mocha/ClassMethods.html#any_instance-instance_method
