### ISSUE TITLE
stubs and expects destroy public_methods(false)

### ISSUE THREAD

**Issue by jakemack** [freerange/mocha#299]
Stubbing or expecting a method on an object destroys the return value of public_methods(false). When you stub/expect a method that exists on an object, public_method(false) starts to return an empty array. Here's a basic test:

```ruby
obj = Object.new
old_methods = obj.public_methods(false)
obj.stubs(:to_yaml)
expect(obj.public_methods(false)).to match_array(old_methods)

```

I'm using Mocha 1.2.1 and rspec 3.5.4

**Comment by floehopper** [comment]
@jakemack: I hope you don't mind, but I've edited the description of this issue slightly to remove some code I think you accidentally left in it and I've enabled Ruby syntax highlighting.

**Comment by floehopper** [comment]
@jakemack:

Since Ruby v2.0, [Mocha versions from v1.2.0](https://github.com/freerange/mocha/blob/master/RELEASE.md#120) have used [prepended modules](http://ruby-doc.org/core-2.0.0/Module.html#method-i-prepend) to stub methods. There are some significant advantages to implementing stubbing this way, but it does have a few side effects - one of which is the one you have found.

The following console session demonstrates what is going on:

### Before stubbing

```
irb> require 'mocha/api'
=> true

irb> obj = Object.new
=> #<Object:0x007ff9db97b468>

irb> obj.__metaclass__.ancestors[0..1].each { |o| puts "\n#{o.inspect}: #{o.instance_methods(false).sort}" }

#<Class:#<Object:0x007ff9db97b468>>: []

Object: [:__is_a__, :psych_to_yaml, :to_yaml, :to_yaml_properties]
```

### After stubbing

```
irb> obj.stubs(:to_yaml)
=> #<Expectation:0x7ff9db91b270 allowed any number of times, not yet invoked: #<Object:0x7ff9db97b468>.to_yaml(any_parameters) >

irb> obj.__metaclass__.ancestors[0..2].each { |o| puts "\n#{o.inspect}: #{o.instance_methods(false).sort}" }

#<Mocha::ClassMethod::PrependedModule:0x007ff9db920ea0>: [:to_yaml]

#<Class:#<Object:0x007ff9db97b468>>: []

Object: [:__is_a__, :psych_to_yaml, :to_yaml, :to_yaml_properties]
```

### After un-stubbing

```
irb> obj.unstub(:to_yaml)
=> [:to_yaml]

irb> obj.__metaclass__.ancestors[0..2].each { |o| puts "\n#{o.inspect}: #{o.instance_methods(false).sort}" }

#<Mocha::ClassMethod::PrependedModule:0x007ff9db920ea0>: []

#<Class:#<Object:0x007ff9db97b468>>: []

Object: [:__is_a__, :psych_to_yaml, :to_yaml, :to_yaml_properties]
```

To summarise, when the `to_yaml` method is stubbed, an instance of `Mocha::ClassMethod::PrependedModule` is prepended and a new (stubbing) `to_yaml` method is defined on it; the underlying original definition of `to_yaml` on `Object` remains unchanged. This stubbing method intercepts calls to `to_yaml` providing the stubbing behaviour. When the method is un-stubbed, the stubbing method on the prepended module is removed and so calls to `to_yaml` are once again handled by `Object#to_yaml`. However, the prepended module remains in place, because it's not currently possible to un-include or un-prepend a module.

It is the presence of this "empty" module which affects the return value you are seeing from `public_methods(false)` - the return value has not been "destroyed" as you put it; it's just that the receiver for that method is now the prepended module and not the object instance itself.

While the behaviour you are seeing isn't ideal, I don't think there's a way to avoid it while still using the prepended module approach. Also while the return value from `public_methods(false)` may have changed, the overall behaviour of the object (after un-stubbing) remains unchanged, the result of `public_methods(true)` remains unchanged, and the methods defined on the object remain unchanged; the *only* difference is that there is an empty prepended module "in front" of the object.

Since using prepended modules offers a number of implementation advantages in Mocha, my initial reaction is that we probably won't attempt to "fix" the behaviour you are seeing. However, I can see that it might be useful to explain how the stubbing mechanism works somewhere in the documentation so that this behaviour is not as surprising. I have opened a [new issue to capture this idea](https://github.com/freerange/mocha/issues/300).

I'm going to mark this issue as "wont-fix" for now, but I'll give it some more thought.

One last question: Is this issue causing you a specific problem or was it just that you were surprised by the behaviour? If it's causing you a specific problem, do let us know and we'll see whether we can help you workaround it.

**Comment by jakemack** [comment]
I think it's fine as "wont-fix." I'm mostly looking for a workaround to get this tested because it is indeed a specific problem. The basic idea is that we have a class hierarchy and the base class defines `method_missing` to discover all instance methods (via `public_methods(false)`) that match a pattern and roll them up into a new method that runs these methods sequentially and returns the return value of the first method to have a "present" value (using Rails `present?`). Basically, if I define `calc_cost_1`, `calc_cost_2`, and `calc_cost_3`, I can call `calc_cost` to call `calc_cost_1` and return the value if it exists, otherwise call `calc_cost_2` and return the value if it exists, otherwise call `calc_cost_3` and return the value. The reason we use `public_methods(false)` is because we want to allow subclasses to have their own, same named sets of methods as the class they inherit from.

It might be simpler to understand with code so here's the gist of it

```ruby
  def method_missing(method_name, *args, &block)
    methods_to_call = public_methods.select {|method_sym| method_sym.to_s.starts_with?('calc_') && method_sym =~ /^#{Regexp.quote method_name}_\d+$/}
    if methods_to_call.present?
      methods_to_call.sort.each do |method_to_call|
        value = send method_to_call
        
        return value if value.present? || value.class == FalseClass
      end

      nil
    else
      super
    end
  end

So, any suggestions on how to test that the individual methods are called in the right order and that nil is returned if none of the individual methods have a present return value would be greatly appreciated.

**Comment by floehopper** [comment]
I'm sorry for the incredibly slow reply. I'm afraid I don't really have any suggestions, other than to say that I wouldn't try to test code like this using mock objects - I would either change the design to make testing using mock objects easier, or I would not use mock objects at all and just test using state-based testing. I'm sorry not to have been more helpful. I'm going to close this issue now. I hope that's OK.
