### ISSUE TITLE
Allow stubbed method to call a proc

### ISSUE THREAD

**Issue by jduff** [freerange/mocha#317]
I thought I would ask before creating a PR, but is there any interest in a `Expectation` method that allows you to specify a proc that is called as the return value? The case I had for this was testing race conditions with transactions, I wanted to stub a method and have it `sleep` so that I could race another thread with it. I couldn't find an easy way to do this with the existing methods in mocha so added this to my test helper which seems to work well:

``` ruby
module Mocha
  class Caller
    def initialize(proc)
      @proc = proc
    end

    def evaluate
      @proc.call
    end
  end

  class Expectation
    def calls(proc)
      @return_values += ReturnValues.new(Caller.new(proc))
      self
    end
  end
end

object = mock()
object.stubs(:stubbed_method).calls(->{sleep(1); 5})
```
If this is a patch that you're interested in I can write a PR and add some documentation. Thanks!

**Comment by floehopper** [comment]
@jduff:

I'm sorry for the slow response. Thanks for raising this issue.

I think this idea has come up before in #213, #230 & #231. You mention wanting to be able to use the proposed functionality to test race conditions with transactions. Would you be able to post an example test to illustrate this? I'd like to properly understand the problem you're trying to solve.

Am I right in thinking, what you're proposing is similar to rspec-mock's [block implementation](https://relishapp.com/rspec/rspec-mocks/v/3-7/docs/configuring-responses/block-implementation)?

**Comment by jduff** [comment]
No worries!

This is very similar to the rspec-mock's block implementation. What I proposed isn't as full featured as theirs (the arguments are not passed to the proc) but it would be straight forward to enable that. I like their block syntax a bit better than the proc version I have as well.

Here's a simplified version of one of the tests I have for the transaction race.

``` ruby
test "race" do
  order = orders(:first)
  assert_nil order.captured_at
  Stripe::Charge.expects(:retrieve).calls(-> {sleep(1); stub(capture: true, captured: true)}).once

  t1 = Thread.new do
    assert order.capture
  end

  t2 = Thread.new do
    assert !order.capture
  end

  [t1, t2].each(&:join)

  assert_not_nil order.reload.captured_at
end
```

I'm not a huge fan of the test tbh, but it did the job to test the locking happening in the `capture` method.

If you have any other questions let me know!

**Comment by floehopper** [comment]
@jduff:

I'm really sorry it's taken me so long to get back to you.

Thanks for sending through your example test. It would be helpful to also see the implementation of `Order#capture` to fully understand what you're trying to do. However, as far as I can see I think you'd be better off using a "fake" implementation of the Stripe service in tests like this rather than trying to use Mocha.

Mocha is intended to be used in *unit* tests for the [Mock Object][] or [Test Stub][] types of [Test Double][], not the [Fake Object][] or [Test Spy][] types. Although it would be possible to extend Mocha to allow the implementation of fakes and spies, I'd prefer to keep it focussed on mocks and stubs. I think providing a fully-fledged solution for fakes and/or spies would be a lot of work.

Something else you should bear in mind is that Mocha is [not currently thread-safe][1].

I'm very happy to continue this conversation and to help you come up with a sensible way to test what you want to test, but as things stand at the moment, I'm not keen to accept a PR of the kind you originally proposed.

[Mock Object]: http://xunitpatterns.com/Mock%20Object.html
[Test Stub]: http://xunitpatterns.com/Test%20Stub.html
[Test Double]: http://xunitpatterns.com/Test%20Double.html
[Fake Object]: http://xunitpatterns.com/Fake%20Object.html
[Test Spy]: http://xunitpatterns.com/Test%20Spy.html
[1]: https://github.com/freerange/mocha/blob/v1.4.0/README.md#thread-safety

**Comment by floehopper** [comment]
I've created [a new issue](https://github.com/freerange/mocha/issues/330) about improving the documentation to explain how Mocha is intended to be used. I'm closing this issue for now. Please let me know if you have any more questions.

**Comment by jduff** [comment]
That makes sense, thanks for explaining!

**Comment by floehopper** [comment]
A relevant discussion continues in #224.
