### ISSUE TITLE
Replace `require 'mocha/minitest'` with `require 'mocha/mini_test` in README.md

### ISSUE THREAD

**Issue by ozgun** [freerange/mocha#324]
Hi,

There is an instruction like `require 'mocha/minitest'` in README.md under "Rails -> Minitest" section.

Adding `require 'mocha/minitest` to `test_helper.rb` produces an error as below:

```
`require': cannot load such file -- mocha/minitest (LoadError)
```

Replacing `require 'mocha/minitest'` with `require 'mocha/mini_test'` fixes the error.

Rails version: 5.2.0rc
mocha version: 1.3.0

Thanks,

**Comment by padi** [comment]
@ozgun noticed this as well, but it seems that in the current master branch of the repo (https://github.com/freerange/mocha/commit/76aad9c2a9620afd0925dba381a12a3b3658745b):
- there's a lib/mocha/minitest.rb; and
- lib/mocha/mini_test.rb is deprecated.

But when you `bundle open mocha` when you install the latest released mocha version, 1.3.0, there's no such file as lib/mocha/minitest.rb,

I bet it's because the latest released version is not the same as `master`. So you have to read the [README for 1.3.0](https://github.com/freerange/mocha/tree/v1.3.0) instead.

**Comment by ozgun** [comment]
@padi thanks, my bad! I'm closing the issue.

**Comment by floehopper** [comment]
@ozgun: Yes, @padi's explanation is correct. Sorry for the confusion and thanks for closing the issue.

@padi: Thanks for helping @ozgun. Much appreciated! 👍
