### ISSUE TITLE
mocha 1.7 introduced regression in protected_attributes tests

### ISSUE THREAD

**Issue by pravi** [freerange/mocha#348]
See https://github.com/rails/protected_attributes/issues/93 its developer thinks the issue is with mocha and now locked to previous version of mocha. If it is not really a regression, please suggest how to fix the above failure.

**Comment by floehopper** [comment]
@pravi I haven't had time to look into this in detail. However, I have reproduced the failing tests by cloning the repo, removing the version constraint on Mocha from `protected_attributes.gemspec` and updating the bundle to use Mocha v1.7.0. I noticed that [`test/test_helper.rb`](https://github.com/rails/protected_attributes/blob/5302e327ed4e84610a4940e4dee85155620977c8/test/test_helper.rb#L3) is not using [the recommended way of setting up Mocha](https://github.com/freerange/mocha/blob/ef428ea285e5c417d8e79c2854150947575373ef/README.md#minitest-1) which is to `require 'mocha/minitest'` rather than `require 'mocha/api'` (in fact I'm not sure the latter has *ever* been a recommended way). When I changed this the tests no longer failed, so I would suggest you try that. Let me know if you have any more questions.

**Comment by pravi** [comment]
@floehopper thanks! that fixed the test failure.

**Comment by floehopper** [comment]
@pravi No problem. Glad to be of help. 👍

**Comment by rafaelfranca** [comment]
Thanks @floehopper
