### ISSUE TITLE
Expected methods not invoked when using Mocha v0.10.5

### ISSUE THREAD

**Issue by LeninGangwal** [freerange/mocha#350]
Our app has a bunch of UTs which works completely fine in other developers' systems, and used to work well in my system too, until I somehow unknowingly screwed it up. I have reinstalled all the dependencies, but somehow the tests aren't passing.

I am getting a "allowed any number of times, not yet invoked" error.

The version of mocha is 0.10.5.

**Comment by floehopper** [comment]
* Are you definitely using the same version of test library and Mocha gems as your colleagues, e.g. if you're using Bundler, are your `Gemfile.lock` files the same?
* Are you using a test library which runs tests in a random order, e.g. MiniTest, RSpec, or Test::Unit? If so, can you obtain a seed value from a successful test run from one of your colleagues and use that to run the tests in the same order on your machine? Do you still see the failure(s).
* Does your codebase use threads or multiple processes and, if so, is it possible the expected method(s) are not being invoked on your machine because of a race condition?
* You are using a _very_ old version of Mocha; is there any way you could consider upgrading to a newer version?

**Comment by floehopper** [comment]
I hope you don't mind, but I've changed the title of this issue to better reflect its content.

**Comment by LeninGangwal** [comment]
The issue has been solved. There was an issue with my test dB as there were some changes made to it during one of the tests I wrote which persisted. Hence reinitializing the dB solved it.

Thanks for your input.
