### ISSUE TITLE
How does yielding from a stubbed method work?

### ISSUE THREAD

**Issue by itmart** [freerange/mocha#351]
I want to test a `retriable` block using the [retriable gem][1]. I'm using mocha and minitest to test this. In my controller, I have a `retriable` block that looks like this:

```ruby
def dashboard
  Retriable.retriable do
    @opened_accounts = @user.fetch_accounts # This fetchs from an external API
  end
  rescue StandardError => e
    render "layouts/_error_message"
  end
end
```

And in my test, I have something like this:

```ruby
test 'expects to retry to get account when API is temporarily down' do
  # Arrange
  api_endpoint = Regexp.new "https://api-link.com/accounts"
  # Using Webmock
  stub_request(:get, api_endpoint).to_raise(Errno::ECONNREFUSED).then
                                  .to_return(body: {accounts: "1,2,3"}.to_json, status: 200)
  User.any_instance.stubs(:fetch_accounts).returns({accounts: "1,2,3"}.to_json)
  Retriable.expects(:retriable).yields(mock).twice
  
  # Act
  get dashboard_url

  # Assert
  assert_template "dashboard/dashboard"
  assert_select ".account-list-item", count: 3
end
```

The part I'm most confused about is for this line:

```ruby
Retriable.expects(:retriable).yields(mock).twice
```

Why do I have to call `.yields(mock)` in order for `@opened_accounts` to be set properly? I found out that if I just do:

```ruby
Retriable.expects(:retriable).twice
```

`@opened_accounts` will be nil when it gets to the view and my last assertion will fail. I'm not sure I understand what's going on completely and have looked up a lot of documentations and SO posts about mocks and stubs but I still have troubles figuring exactly why it has to work this way. Some insights would be very much appreciated!

  [1]: https://github.com/kamui/retriable

**Comment by floehopper** [comment]
@itmart I hope you don't mind, but I've reformatted the description of this issue to enable Ruby syntax highlighting.

**Comment by itmart** [comment]
@floehopper Of course, thank you for doing that! I totally forgot I can enable syntax highlighting in GitHub. I also think the new title represents the question a lot better, thanks!

**Comment by floehopper** [comment]
At it's core the _real_ implementation of the `Retriable.retriable` method  will somehow invoke the block that is passed in (which in your case includes the call to `User#fetch_accounts` and the assignment to `@opened_accounts`). So with no mocking/stubbing in place, the reason the code in this block is normally executed is because of a statement like `yield` or `block.call` being executed within `Retriable.retriable`. In fact, I suspect it's actually [this line][1].

The main thing to understand is that when you stub (or expect) a method using Mocha, you are temporarily *replacing* the implementation of that method. And if you setup a stub _without_ calling [`Expectation#yields`][2] (e.g. `Retriable.expects(:retriable).twice`), then it's as if you've defined a method which ignores any block passed to it, just like any simple Ruby method. This is probably best illustrated by an example:

```ruby
irb> def foo; end
=> :foo
irb> foo { raise 'boom!' }
=> nil # exception is *not* raised, because block is *not* called
```

However, if you setup a stub and you _do_ call `Expectation#yields` (e.g. `Retriable.expects(:retriable).yields(mock).twice`), then any block passed in will be invoked with the supplied parameters. The equivalent in simple Ruby would be something like this:

```ruby
irb> def foo; yield; end
=> :foo
irb> foo { raise 'boom!' }
=> RuntimeError (boom!) # exception *is* raised, because block *is* called
```

I hope you can see how this explains why you need to call `Expectation#yields` in your test in order for `User#fetch_accounts` to be called and for the result to be assigned to `@opened_accounts`.

As an aside, I think your test is more complicated than it needs to be, but I'll try to explain why I think that in a separate comment.

[1]: https://github.com/kamui/retriable/blob/d66e4db725f39fd4723ae1ba7cb286aa36e8183a/lib/retriable.rb#L61
[2]: https://gofreerange.com/mocha/docs/Mocha/Expectation.html#yields-instance_method

**Comment by itmart** [comment]
Thank you! I was reaching the same conclusions myself, but originally I had thought this was some `Mocha` magic that I wasn't understanding completely, not `Retriable`. Your explanation definitely explains it a lot clearer and I think I understand it now!

I will also gladly accept any suggestions you have for my test! It's my first time using `Mocha` so I wasn't too sure if that's a good way to use it either so any suggestions would be greatly appreciated!

**Comment by floehopper** [comment]
Your test seems a bit muddled to me. I think you need to decide at what level you want to stub things out - EITHER stub `User#fetch_accounts` using Mocha OR stub the HTTP request to the API using WebMock; there's no need to do both!

Also, I might be missing something, but it's not obvious to me that it's very useful to stub `Retriable.retriable`, is it?

So I'm not sure I would use Mocha at all in this case. I'd probably do something like this:

```ruby
test 'expects to retry to get account when API is temporarily down' do
  # Arrange
  api_endpoint = Regexp.new "https://api-link.com/accounts"
  stub_request(:get, api_endpoint)
    .to_raise(Errno::ECONNREFUSED).then
    .to_return(body: {accounts: "1,2,3"}.to_json, status: 200)

  # Act
  get dashboard_url

  # Assert
  assert_template "dashboard/dashboard"
  assert_select ".account-list-item", count: 3
end
```

I've never used Retriable myself, but as I understand it, the sequence would be something like this:

1. `Retriable.retriable` invokes the block passed into it
2. `User#fetch_accounts` is called
3. WebMock raises an exception
4. `Retriable.retriable` rescues the exception
5. `Retriable.retriable` invokes the block a second time
6. `User#fetch_accounts` is called again
7. WebMock responds with a 200 OK and a JSON body
8. `User#fetch_accounts` returns successfully
9. The return value is assigned to `@opened_accounts`
10. The "dashboard" template is rendered

I believe this would only work if you have the call to `User#fetch_accounts` and the assignment wrapped in the call to `Retriable.retriable` wouldn't it? So this test *is* checking that the implementation can handle an error response from the API.

If you don't want to use WebMock, you could use Mocha as follows:

```ruby
test 'expects to retry to get account when API is temporarily down' do
  # Arrange
  User.any_instance.stubs(:fetch_accounts)
    .raises(Errno::ECONNREFUSED).then
    .returns({accounts: "1,2,3"}.to_json)

  # Act
  get dashboard_url

  # Assert
  assert_template "dashboard/dashboard"
  assert_select ".account-list-item", count: 3
end
```

Again, I think this test will only pass if you wrap the call to `User#fetch_accounts` and the assignment in the call to `Retriable.retriable`.

If you _really_ wanted to stub `Retriable.retriable` then I don't think that's possible with Mocha, because there's no way to tell a stub to yield to a block, rescue an exception, and then yield to the block again. But as I've tried to explain above, I don't think that stubbing `Retriable.retriable` is useful.

I hope that makes sense. Let me know if you have any more questions.

**Comment by floehopper** [comment]
> I had thought this was some `Mocha` magic that I wasn't understanding completely, not `Retriable`

The only thing that a bit different about `Retriable.retriable` is that it potentially invokes the block passed into it multiple times and it can rescue exceptions raised by the block.

With Mocha it *is* possible to stub a method and have it invoke the block passed in multiple times by using [Expectation#multiple_yields](https://gofreerange.com/mocha/docs/Mocha/Expectation.html#multiple_yields-instance_method). However, it's *not* possible to have the stub rescue an exception raised by the block.

**Comment by floehopper** [comment]
I'm going to close this issue. Please re-open if you don't feel I've addressed you questions sufficiently.

**Comment by itmart** [comment]
I see, we were thinking of just using `WebMock` itself, but wanted to make sure the `Retriable` block is being ran twice. That's why we started looking into `Mocha` and saw that we could do `Retriable.expects(:retriable).twice`. But no accounts would show if we do just that and that was how we ended up with that test that uses both `Mocha` and `WebMock`.

If I understand it correctly, the `retriable` block in my test is *not* rescuing the exception raised by `WebMock` and is not re-trying anything, is that correct? If that's the case, would you mind explain why 
``` ruby
Retriable.expects(:retriable).yields(mock).twice
```
would work, but when we tried to do
``` ruby
Retriable.expects(:retriable).yields(mock).once
```
it failed and said the method was invoked twice?

**Comment by floehopper** [comment]
> I see, we were thinking of just using `WebMock` itself, but wanted to make sure the `Retriable` block is being ran twice.

In my versions of the test, I can't see how it would be possible for the block passed into `Retriable.retriable` to only be executed once, but for the test to pass. If the block was only executed once, then you would either see an exception being raised and/or `@opened_accounts` would not be assigned a sensible value. So although it's not a **direct** test that the block passed to `Retriable.retriable` is executed twice, to me it's good enough to check the retry behaviour is working.

> That's why we started looking into `Mocha` and saw that we could do `Retriable.expects(:retriable).twice`.

I think you might be a bit confused here. If I've understood correctly how `Retriable.retriable` works, then it is only invoked once according to the code you have posted. It's **the block passed into `Retriable.retriable`** which is potentially invoked more than once.

By calling `Expectation#twice`, you are saying that the `Retriable.retriable` method itself should be invoked twice. It's not obvious to me how that is happening, but perhaps you haven't posted all the code and there is another call to `Retriable.retriable` that I cannot see...?

> But no accounts would show if we do just that and that was how we ended up with that test that uses both `Mocha` and `WebMock`.

I think the reason no accounts were showing up was because you had stubbed `Retriable.retriable`, but not setup the stub to yield to the block passed into it. This meant that the line inside the block was never being executed. So I'm pretty confident this is unrelated to the use of Mocha/WebMock - you only need one or the other.

> If I understand it correctly, the `retriable` block in my test is *not* rescuing the exception raised by `WebMock` and is not re-trying anything, is that correct?

I'm not sure that's quite right. Since the real implementation of `User#fetch_accounts` is being stubbed, the remote HTTP request is never made and the WebMock stub has no effect. Thus WebMock is never raising an exception. However, if WebMock did somehow raise an exception, the stubbed version of `Retriable.retriable` would not rescue the exception or retry.

> If that's the case, would you mind explain why `Retriable.expects(:retriable).yields(mock).twice` would work, but when we tried to do `Retriable.expects(:retriable).yields(mock).once` it failed and said the method was invoked twice?

My best guess would be that `Retriable.retriable` (**not the block inside it**) is somehow being called twice. Have you posted all the code here, or have you simplified it for the purposes of the issue?

As an aside, I don't think you need to pass `mock` into `Expectation#yields` in this case - the block passed into `Retriable.retriable` does not accept any arguments.

**Comment by itmart** [comment]
I simplified it for the purposes of this issue because the entire thing is pretty lengthy and I don't think they are too relevant. But I've checked everything and nothing is really calling `retriable` again, so that still remains a mystery to me. I'll check it again though.

> It's **the block passed into `Retriable.retriable`** which is potentially invoked more than once.

If I understand this correctly, it was incorrect to expect `Retriable(:retriable)` to be called twice in the first place? 

I think this has been very helpful and I'll do some re-factoring on the test and use your suggestions. Thank you so much for your time and have a good day!

**Comment by floehopper** [comment]
> I simplified it for the purposes of this issue because the entire thing is pretty lengthy and I don't think they are too relevant. But I've checked everything and nothing is really calling `retriable` again, so that still remains a mystery to me. I'll check it again though.

Might the controller action itself somehow be called twice in the test, perhaps in some setup/before block?

>> It's **the block passed into `Retriable.retriable`** which is potentially invoked more than once.
>
> If I understand this correctly, it was incorrect to expect `Retriable(:retriable)` to be called twice in the first place? 

I think that's right (as long as I've understood correctly how `Retriable` works!)

> I think this has been very helpful and I'll do some re-factoring on the test and use your suggestions.  Thank you so much for your time and have a good day!

No worries. Glad to be of help.
