### ISSUE TITLE
Mocha teardown should be done as soon as possible

### ISSUE THREAD

**Issue by cyrilchampier** [freerange/mocha#355]
Here is a simplified version of my problem:
```
class AccountTest < ActiveSupport::TestCase
  setup { puts "SETUP: env something is nil" if Figaro.env.something.nil? }
  teardown { puts "TEARDOWN: env something is nil" if Figaro.env.something.nil? }

  def test_is_ok
    Figaro.env.stubs(:something).returns(1)
    assert "everything is fine"
  end
end
```

The test will only puts on setup, because [mocha teardown is done "after teardown"](https://github.com/freerange/mocha/blob/master/lib/mocha/integration/mini_test/adapter.rb#L47) as [described on the global behavior](https://github.com/freerange/mocha/blob/master/lib/mocha/hooks.rb#L37).

I do not understand why it should be called `after any "teardown" code`.

Given that
* teardown code can rely on things susceptible to be stubbed
* that Mocha is independent on such relations
should not mocha be the first thing to be "teardowned"?

I solved my problem by moving [the `mocha_teardown` call from `Mocha::Integration::MiniTest.after_teardown`](https://github.com/freerange/mocha/blob/master/lib/mocha/integration/mini_test/adapter.rb#L47) to  [`Mocha::Integration::MiniTest.before_teardown`](https://github.com/freerange/mocha/blob/master/lib/mocha/integration/mini_test/adapter.rb#L40).

Would you accept a PR modifying this behavior?

**Comment by floehopper** [comment]
@cyrilchampier 

Thanks for taking the time to illustrate your issue with some example code.

I think the original logic of doing it this way was that since Mocha is setup before all other setup blocks/methods, it should be torn down after all other teardown blocks/methods. I feel that this keeps things "symmetric".

While I understand that you've found the behaviour confusing, I suspect that other people might find the behaviour that you are suggesting confusing too. And you're the first person in 10 years who has raised this issue!

Making the change you suggest would involve deprecating the current behaviour somehow and making a new major release, because it might well break tests in a *lot* of projects!

Furthermore I think you should still be able to solve your problem by making use of [`Mocha::ObjectMethods#unstub`][1] in the teardown method. Does that make sense?

So given all the above, I don't want to make the change you suggest and I'm going to close this issue. I hope you understand.

[1]: https://mocha.jamesmead.org/Mocha/ObjectMethods.html#unstub-instance_method

**Comment by floehopper** [comment]
I've added [an issue][1] to improve the documentation to try to avoid anyone else being similarly confused by the behaviour.

[1]: https://github.com/freerange/mocha/issues/356

**Comment by cyrilchampier** [comment]
Thanks for your response.
I do understand the problem of modifying this behavior after 10 years.

That means that the only correct solution is:
```
class AccountTest < ActiveSupport::TestCase
  setup { puts "SETUP: env something is nil" if Figaro.env.something.nil? }
  teardown { puts "TEARDOWN: env something is nil" if Figaro.env.something.nil? }

  def test_is_ok
    Figaro.env.stubs(:something).returns(1)
    assert "everything is fine"
    Figaro.env.unstub(:something)
  end
end
```

I will let it know in our team.

**Comment by floehopper** [comment]
@cyrilchampier OK - thanks for understanding. I was thinking about it a bit more and if you _really_ wanted to, I think you could create your own alternative version of `Mocha::Integration::MiniTest::Adapter` which implemented the teardown sequence the way you wanted to. Instead of requiring `mocha/minitest`, you'd need to include your adapter into the appropriate test superclass, probably `Minitest::Test`. Let me know if this sounds interesting and I can try to help you implement it.

**Comment by cyrilchampier** [comment]
Thanks for the suggestion. I am still hesitating between doing this to correct the problem globally (but only for stub conflicts) and trying to educate all our devs so that they write proper teardown. Your solution seems simpler though!
