### ISSUE TITLE
Consider renaming mock instance variable in Invocation

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#415]
See [this review comment](https://github.com/freerange/mocha/pull/411#discussion_r347093423).

Possibly rename `@mock` to `@receiver` if appropriate.

**Comment by nitishr** [comment]
I thought this made sense until the time I tried going a step further and changing `receiver` to `receiver_name` as [shown here](https://github.com/freerange/mocha/compare/master...nitishr:rename-mock-instance-variable-in-invocation#diff-de1dfd5840f4200e083b87fdfedfa236L11-L44). That fails because the `receiver_name` is derived from `inspect/mocha_inspect`-ing the receiver. I'm not sure whether being 'inspectable' in that sense is the responsibility of just any generic 'receiver', or just mocks?

**Comment by floehopper** [comment]
OK. Thanks for investigating. I'll close this.
