### ISSUE TITLE
Question: can Mocha::Central#unstub_all be used in test_helper to unstub everything?

### ISSUE THREAD

**Issue by cnadeau** [freerange/mocha#498]
I'm trying to figure if it's possible to do the same thing as [jest.clearAllMocks()](https://jestjs.io/docs/en/jest-object#jestclearallmocks) in JS

I'd love to call `unstub_all` in test_helper's `teardown` method

Thanks!

**Comment by floehopper** [comment]
@cnadeau Hi. Thanks for your question. Can you explain a bit more about why you want to be able to do this? In case you didn't already know, `Mocha::Central#unstub_all` is automatically called at the end of every test if you are using the integrations with test-unit, minitest, or rspec. Are you using one of those integrations? And is this automatic behaviour not sufficient for your needs? If not, can you explain why not? Many thanks.

**Comment by cnadeau** [comment]
Thanks for the quick answer @floehopper. I did not see that Central.unstub_all was called after each test in the documentation (or I totally missed it)

I joined a projet that is using `minitest` where `unstub` are manually reset after each test and I was wondering why.

I was told that it must be done manually . Maybe it was true 7 years ago, but I'm glad to read it's now automagic! 

Thanks for your time and for this great project!

**Comment by floehopper** [comment]
@cnadeau 

No worries. Glad I could help. I've created #499 to remind us to try to make this clearer in the documentation.

> Maybe it was true 7 years ago, but I'm glad to read it's now automagic!

Hmm. I believe it's always been the case from day one! However, there's a chance the minitest integration was broken in some earlier versions, because it relied heavily on monkey-patching which was very brittle.

Anyway, let me know if it's not working for you now! You should be able to test it fairly easily.
