### ISSUE TITLE
Mock array parameters ignoring the order

### ISSUE THREAD

**Issue by sundarraja** [freerange/mocha#505]
```
object = mock()
object.expects(:method_1).with([2, 1])
object.method_1([1, 2])
```
Can we make this pass with any of the ParameterMatchers? I could think of `object.expects(:method_1).with(includes(2, 1))`? But this does not guarantee that the parameter includes **only** 1 and 2.

**Comment by floehopper** [comment]
@sundarraja I would recommend using the block form of [`Expectation#with`](https://mocha.jamesmead.org/Mocha/Expectation.html#with-instance_method) to implement a custom matcher along the following lines:

```ruby
require 'bundler/setup'
require 'minitest/autorun'
require 'mocha/minitest'

class Foo < Minitest::Test
  def test_foo
    object = mock()
    object.expects(:method_1).with(&array_containing_exactly([2, 1]))
    object.method_1([1, 2])
  end

  private

  def array_containing_exactly(expected_array)
    -> actual_array { actual_array.sort == expected_array.sort }
  end
end
```

Does that make sense? Please close this issue if this solves your problem. Thanks.

**Comment by sundarraja** [comment]
@floehopper What if there are additional parameters? Is it possible to mix the block form with other matches?

```object = mock()
object.expects(:method_1).with("something", [2, 1])
object.method_1("something", [1, 2])

**Comment by floehopper** [comment]
@sundarraja:

It's not possible to mix the block form with the other matchers. And I don't think I'd want to support that mechanism, because the code wouldn't be very easy to read.

A couple of options come to mind...

1. If you only need to match this combination of parameters in a few places, make the block matcher in my previous example more sophisticated, e.g.

```ruby
  def test_foo
    object = mock()
    object.expects(:method_1).with(&something_and_array_containing_exactly('something', [2, 1]))
    object.method_1([1, 2])
  end

  private

  def something_and_array_containing_exactly(expected_something, expected_array)
    -> something, array { something == expected_something && array.sort == expected_array.sort }
  end
```

2. If you want more flexibility define a more fully-fledged matcher so you can combine it with other matchers, e.g.

```ruby
  class ContainsExactly < Mocha::ParameterMatchers::Base
    def initialize(*items)
      @items = items
    end

    def matches?(available_parameters)
      available_parameters.shift.sort == @items.sort
    end

    def mocha_inspect
      "contains_exactly(#{@items.mocha_inspect(false)})"
    end
  end

  def contains_exactly(*items)
    ContainsExactly.new(*items)
  end

  def test_foo
    object = mock()
    object.expects(:method_1).with('something', contains_exactly(1, 2))
    object.method_1([1, 2])
  end
```

Note that the `ContainsExactly` matcher I've implemented here is just a quick hack - there are probably a bunch of edge cases which I haven't covered, but it might be good enough for what you want.

Does that make sense? Please close this issue if this solves your problem. Thanks.

**Comment by sundarraja** [comment]
Thanks, that’s helpful :)
