### ISSUE TITLE
[Help] Mocking and Stubbing Stripe gem

### ISSUE THREAD

**Issue by alvincrespo** [freerange/mocha#509]
Hi there! I was hoping to get some help with mocking the stripe gem. I currently have the following setup:

```
require 'mocha'

session_mock = Mocha::Mock.new('checkout_session')
session_mock.stubs(:create).returns({ id: "SOMEID" })

Stripe::Checkout::Session.stubs(:new).returns(session_mock)
```

But I keep getting this error:

```
(byebug) Stripe::Checkout::Session.stubs(:new)
*** NoMethodError Exception: undefined method `last' for nil:NilClass
```

I'm not sure why?

I had the following previously:

```
Stripe::Checkout::Session.any_instance.stubs(:create).returns({ id: "Something" })
```

That seems to give me the same issue. I'm missing something and can't really pin-point it. Any help would be fantastic! 

BTW - this library rocks. I absolutely love it. Thank you!

**Comment by floehopper** [comment]
@alvincrespo 

I need a bit more information to work out what's going on...

1. Are you running this code inside a Minitest test or an RSpec spec? Mocha isn't designed to run outside one of these environments.
2. You need to `require 'mocha/minitest'` or `require 'mocha/test_unit'` _after_ requiring the relevant test library. `require 'mocha'` on its own doesn't setup any of the integration with the test library.
3. You should create a mock object using the [`Mocha::API#mock`](https://mocha.jamesmead.org/Mocha/API.html#mock-instance_method) method, rather than instantiating an instance of `Mocha::Mock` directly.
4. When do you see that `NoMethodError`? Is it when you run just the code you posted or is there some other code you're not showing here?

I've run a simple example test and I don't see any exception when I run it:

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'minitest'
gem 'mocha'
gem 'stripe'
```

```ruby
# foo_test.rb
require 'bundler/setup'
require 'minitest/autorun'
require 'mocha/minitest'
require 'stripe'

class Foo < Minitest::Test
  def test_foo
    session_mock = mock('checkout_session')
    session_mock.stubs(:create).returns({ id: "SOMEID" })
    Stripe::Checkout::Session.stubs(:new).returns(session_mock)
    session = Stripe::Checkout::Session.new
    assert_equal({:id=>"SOMEID"}, session.create)
  end
end
```

**Comment by alvincrespo** [comment]
@floehopper Thanks for all this info - this is super helpful. Going to try and dig in a bit more.

I'm currently using [cypress-on-rails](https://github.com/shakacode/cypress-on-rails) and I'm trying to mock out the Stripe library in an `appScenario`:

https://github.com/shakacode/cypress-on-rails/blob/692877887fd1e76fe64e10e7635466f69127b968/lib/generators/cypress_on_rails/templates/spec/cypress/support/on-rails.js#L21-L23

I believe behind the scenes, they're just evaluating the scenario files - I need to verify that. I was hoping to use mock so that I could easily just simulate the lib in my E2E tests.

**Comment by alvincrespo** [comment]
@floehopper Quick update. I found this section in the README which basically helped clear things up for me: https://github.com/freerange/mocha#other-test-framework

To get this to work, I do two things:

1. Include `mocha/api` in `spec/cypress/cypress_helper.rb`
2. Setup my scenario  like so:

```
module Cypress
  class ScenarioSetup
    include Mocha::API

    def setup
      mocha_setup
      mocha_verify

      # TEST SETUP

      # MOCKS AND STUBS HERE
      Stripe::Checkout::Session.stubs(:create).returns(OpenStruct.new({ id: "test_session_id" }))

      nil
    end
  end
end

Cypress::ScenarioSetup.new.setup

```

Now, anytime I need to mock/stub items out - I can use mocha! 🎆 🎆 🎆 

This was my first exploring/implementing mocking on the Ruby/Rails side for my E2E tests - so really appreciate your help with this!

**Comment by floehopper** [comment]
@alvincrespo:

Oh, I see. Well done for getting that working. However, your code isn't _quite_ right.

If you haven't seen it already, it would be worth having a read of the documentation for [`Mocha::Hooks`](https://mocha.jamesmead.org/Mocha/Hooks.html). This module is included in `Mocha::API` and provides the `mocha_setup`, `mocha_verify` & `mocha_teardown` methods. It's not completely clear from this documentation, but:

* you should call `mocha_setup` before any of your test code executes (which you have done correctly ✅ );
* you should call `mocha_verify` after all of your test code has executed (your'e calling this too early ❌ , but it isn't currently causing a problem because you haven't called `Mocha::Mock#expects` or `Mocha::ObjectMethods#expects`)
* you should **ensure** that `mocha_teardown` is called after all of your test code has executed even if an exception is raised (you're not currently calling this at all ❌)

I hope that makes sense - please re-open this issue if you have any more questions about it. I've opened #511 to try to improve the docs in this area based on your experience.

**Comment by alvincrespo** [comment]
@floehopper Oh - this is super awesome info! Ok. I'll take some time today to properly implement in our app. 

Thanks for taking your time to explain this. 👏
