### ISSUE TITLE
`with` not working as expected.

### ISSUE THREAD

**Issue by aaricpittman** [freerange/mocha#523]
I have a tree structure and wrote a method `crawl` that takes a block. For each node in the tree, it will call the block passing it the node, the node's parent, and the level. I'm trying to write a test for this method and have the following.

```ruby
prc = Proc.new {}
prc.expects(:call).once.with(subject, nil, 0)
prc.stubs(:call)

subject.crawl(&prc)
```

This fails with a `expected exactly once, invoked never` message. So, I tried to rewrite using the `with` block syntax like so.

```ruby
prc = Proc.new {}
prc.expects(:call).once.with { |node, parent, level| node == subject && parent == nil && level == 0 }
prc.stubs(:call)

subject.crawl(&prc)
```

And I got the same failure. I tried placing a `binding.pry` inside the `with` block and verified that the `node == subject && parent == nil && level == 0` statement returns `true`.

What am I doing wrong?

**Comment by floehopper** [comment]
Hi. This is relatively common source of confusion e.g. #171.

From [this section of the README](https://mocha.jamesmead.org/index.html#label-Expectation+matching+-2F+invocation+order):

> When a method is invoked on a mock object, the mock object searches through its expectations from newest to oldest to find one that matches the invocation. After the invocation, the matching expectation might stop matching further invocations.

And from the "gotchas" in [the documentation](https://mocha.jamesmead.org/Mocha/Mock.html) for `Mocha::Mock`:

> if you create an expectation and then a stub for the same method, the stub will always override the expectation and the expectation will never be met.

In your case, the stub is the newest and so matches before the expectation. And since it's a stub with no expected invocation count the matching will never be exhausted. So the expectation will never be invoked and thus is never satisfied.

Does that help?

**Comment by floehopper** [comment]
You're welcome! 👍
