### ISSUE TITLE
Expectations with extra arguments are now "unexpected invocations"

### ISSUE THREAD

**Issue by cpjmcquillan** [freerange/mocha#667]
First of all, thanks for maintaining `mocha`! 💚

I'm not sure if this is a regression, or expected behaviour now.

Behaviour changed in v2.4.3.

Before, I could do something like this:

```ruby
mock = mock()
mock
  .expects(:method)
  .with(
    "test",
    hello: "world",
    goodbye: "world"
  )
mock.method(
  "test",
  hello: "world",
  goodbye: "world",
  hello_again: "world"
)
```

and the test would pass.

Now, it fails.

If this is a regression I'm happy to fix it, but I don't want to do any unnecessary work!

Let me know if you need any more information.

**Comment by cpjmcquillan** [comment]
> Do you know what version of Mocha you were using in the "before" times?

It passes is v2.4.2

**Comment by floehopper** [comment]
> It passes in v2.4.2

Yes, but my suspicion is that v2.4.2 was a release that contained the original regression which was introduced in v2.2.0 (released on 10 Apr 2024) and fixed in v2.4.3 (released on 22 Jul 2024). When I have a bit of time I will check this myself, but let me know if you work it out before me.

If my understanding is correct, then I won't be regarding the change described in this issue as a regression. I realise this is all very confusing and I regret that the original problem wasn't spotted sooner.

**Comment by floehopper** [comment]
If my understanding is correct, then you should be able to obtain the behaviour you want by using [`ParameterMatchers#has_entries`](https://mocha.jamesmead.org/Mocha/ParameterMatchers.html#has_entries-instance_method) as follows:

```ruby
mock = mock()
mock.expects(:method).with("test", has_entries(hello: "world", goodbye: "world"))
mock.method("test", hello: "world", goodbye: "world", hello_again: "world")
```

**Comment by cpjmcquillan** [comment]
Was just about to reply with the same. Thank for the context and help 👌
